[package]
name = "hoard-derive-tests"
version = "0.1.0"
authors = ["Peter Todd <pete@petertodd.org>"]
edition = "2018"

[dependencies]
leint = { path = "../leint" }
hoard = { path = "../hoard" }
hoard-derive = { path = "../hoard-derive" }

[dev-dependencies]
