[workspace]
members = [
	"singlelife",
	"leint",
	"owned",

	"sliceinit",

	"hoard",
#	"hoard-derive",
#	"hoard-derive-tests",

	"proofmarshal-core",
 	"proofmarshal-collections",
#	"proofmarshal-derive",
# 	"proofmarshal-derive-tests",

#	"tests",
]
