[workspace]
members = [
	"nonzero",
	"sliceinit",
	"pointee",

	"verbatim",
	"verbatim_derive",
	"verbatim_derive/test",

	"persist",
	"persist_derive",
	"testpersist",

	"proofmarshal",
	"proofmarshal_derive",

	"tests",
]
