[workspace]
members = [
	"singlelife",
	"leint",
	"owned",

	"sliceinit",

	"hoard",
	"hoard-derive",
	"hoard-derive-tests",

	"proofmarshal-core",
	"proofmarshal-derive",
 	"proofmarshal-derive-tests",
	"proofmarshal-collections",

#	"tests",
]
