[package]
name = "proofmarshal-core"
version = "0.1.0"
authors = ["Peter Todd <pete@petertodd.org>"]
edition = "2018"

[dependencies]
hoard = { path = "../hoard" }

thiserror = "1.0.9"
static_assertions = "1.1.0"
sha2 = "0.9.2"
hex-literal = "0.3.1"

[dev-dependencies]
dropcheck = "0.1.1"
