[package]
name = "hoard-derive"
version = "0.1.0"
authors = ["Peter Todd <pete@petertodd.org>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0.11"
synstructure = "0.12.3"

[dev-dependencies]
hoard = { path = "../hoard" }
